package com.dstrube.puzzlers;

/*
commands to compile and run:
from /Users/dstrubex/Projects/java
javac -d /Users/dstrubex/Projects/java/bin com/dstrube/puzzlers/Puzzle15.java
java -cp /Users/dstrubex/Projects/java/bin com.dstrube.puzzlers.Puzzle15

*/

//Try this with only one slash in front of "units":
/**
 * Generated by the IBM IDL-to-Java compiler, version 1.0
 * from F:\TestRoot\apps\a1\\units\include\PolicyHome.idl
 * Wednesday, June 17, 1998 6:44:40 o'clock AM GMT+00:00
 */
public class Puzzle15{
	//Hello Whirled
	
	public static void main(String[] args){
		broken();
		fixed();
	}
	
	public static void broken() {
		System.out.print("Hell");
		System.out.println("o world");
	}
	public static void fixed() {
//	Unicode escapes must be well formed, even if they're in comments.
//	E.g., just one slash in front of "units" here breaks stuff:
	//from F:\TestRoot\apps\a1\\units\include\PolicyHome.idl
	
	//If you do want a unicode character, like this:
//	This algorithm is due to Peter von der Ah\u00E9.
	//then use HTML entity escape where possible instead, like so: 
//	This algorithm is due to Peter von der Ah&eacute;.

	//Also, don't put Windows file paths into comments in generated Java source files, 
	//or anything else that might include "\" followed by "u"
 	}
	
}